Updates
CIRCLES-consortium/CIRCLES-consortium.github.io pull request #1
Opened 2022-02-11 00:12 UTC by rileywagner

2022-02-12 01:52 UTC, liljonnystyle requested changes
I think a couple new people to add as well.
- Han Wang, PhD student, UCB
- Adit Shah, Undergrad student, UCB
- Mostafa Ameli, Visiting Professor (?), UCB
- Mikail Mahmood, Undergrad student, Rutgers
- Shengquan Xiang, ?, ?
- Lee Smith, TDOT (and remove/move Brad Freeze?)

Maria Laura will also be adding another postdoc in ~1-2 months

2022-02-12 01:52 UTC, liljonnystyle commented on about.html
> +                                        <small class="text-muted">Postdoctoral Researcher, Vanderbilt University</small>
is he a postdoc or a researcher now?

2022-02-12 01:52 UTC, liljonnystyle commented on about.html
> +<!--                                 TODO update title and affiliation for Maria Laura Delle Monache -->
ah yes, we should probably put her as a PI at UC Berkeley.

also we need to add her new PhD student, Han Wang (I'll email and CC you)

2022-02-16 20:18 UTC, rileywagner commented on about.html
> +                                        <small class="text-muted">Postdoctoral Researcher, Vanderbilt University</small>
updated title to Research & Development Scientist

2022-02-16 20:18 UTC, rileywagner commented on about.html
> +<!--                                 TODO update title and affiliation for Maria Laura Delle Monache -->
relocated Maria Laura as a Co-PI at UC Berkeley
Added Han Wang

2022-03-03 19:07 UTC, closed without merging